In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('Data .csv')

In [4]:
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [6]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [10]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [12]:
y_pred=regressor.predict(x_test)
np.set_printoptions(precision=2)

In [13]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[457.26 458.96]
 [466.72 463.29]
 [440.37 435.27]
 ...
 [476.41 476.22]
 [424.62 440.29]
 [463.91 467.92]]


In [14]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9321860060402447

In [15]:
from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(x,y)

LinearRegression()

In [19]:
from sklearn.preprocessing import PolynomialFeatures
polyreg=PolynomialFeatures(degree=2)
x_poly=polyreg.fit_transform(x)
lin_reg_2=LinearRegression()
lin_reg_2.fit(x_poly,y)

LinearRegression()

In [23]:
y_pred_poly= lin_reg_2.predict(polyreg.transform(x_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_poly.reshape(len(y_pred_poly),1), y_test.reshape(len(y_test),1)),1))


[[456.17 458.96]
 [463.62 463.29]
 [438.88 435.27]
 ...
 [476.96 476.22]
 [428.93 440.29]
 [463.65 467.92]]


In [24]:
r2_score(y_test,y_pred_poly)

0.9406108918154984

In [25]:
#SVR

In [33]:
y_train=y_train.reshape(len(y_train),1)

In [34]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_y=StandardScaler()
X_train=sc_x.fit_transform(x_train)
Y_train=sc_y.fit_transform(y_train)

In [36]:
from sklearn.svm import SVR
svr_regressor=SVR(kernel='rbf')
svr_regressor.fit(X_train,Y_train)

C:\Users\Home\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

In [40]:
y_pred_svr = sc_y.inverse_transform(svr_regressor.predict(sc_x.transform(x_test)))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_svr.reshape(len(y_pred_svr),1), y_test.reshape(len(y_test),1)),1))

[[456.98 458.96]
 [463.67 463.29]
 [437.52 435.27]
 ...
 [476.33 476.22]
 [432.91 440.29]
 [464.26 467.92]]


In [41]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_svr)

0.9479978713795594

In [42]:
#Decision tree
from sklearn.tree import DecisionTreeRegressor
regressor_dec = DecisionTreeRegressor(random_state = 0)
regressor_dec.fit(x_train, y_train)

DecisionTreeRegressor(random_state=0)

In [43]:
y_pred_dec = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_dec.reshape(len(y_pred_dec),1), y_test.reshape(len(y_test),1)),1))

[[457.26 458.96]
 [466.72 463.29]
 [440.37 435.27]
 ...
 [476.41 476.22]
 [424.62 440.29]
 [463.91 467.92]]


In [44]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_dec)

0.9321860060402447

In [45]:
#random forest regression

In [46]:
from sklearn.ensemble import RandomForestRegressor
regressor_forest = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor_forest.fit(x_train, y_train)

<ipython-input-46-2bf34b2a8b63>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor_forest.fit(x_train, y_train)


RandomForestRegressor(n_estimators=10, random_state=0)

In [47]:
y_pred_forest = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_forest.reshape(len(y_pred_forest),1), y_test.reshape(len(y_test),1)),1))

[[457.26 458.96]
 [466.72 463.29]
 [440.37 435.27]
 ...
 [476.41 476.22]
 [424.62 440.29]
 [463.91 467.92]]


In [48]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_forest)

0.9321860060402447